# Repository
repo_name: intel-secl
repo_url: https://github.com/intel-secl/intel-secl
site_name: Intel® SecL-DC
plugins:
  - search 
  - mkdocs-nav-enhancements
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`


nav: 
  - Home:
    - Intel® Security Libraries for Data Center (Intel® SecL-DC): index.md
  - Product Guide: 
      - Foundational and Workload Security:
        -  Product Guide: product-guides/Foundational & Workload Security/01.md
        -  Introduction: product-guides/Foundational & Workload Security/02 Introduction.md
        -  Intel® Security Libraries Components: product-guides/Foundational & Workload Security/20 Intel® Security Libraries Components.md
        # -  Building Binary Installers: product-guides/Foundational & Workload Security/22 Building Binary Installers.md
        -  Hardware Security Technology Considerations: product-guides/Foundational & Workload Security/23 Hardware Security Technology Considerations.md
        -  Building the Intel SecL-DC Container Images: product-guides/Foundational & Workload Security/23.9 Building the Intel SecL-DC Container Images.md
        -  Deploying Intel SecL-DC Using Helm: 
              -  Deploying Intel SecL-DC Using Helm: product-guides/Foundational & Workload Security/24 Deploying Intel SecL using Helm.md
              -  Deploying Intel SecL Use Cases Using Helm: product-guides/Foundational & Workload Security/25 Deploying Intel SecL Use Cases Using Helm.md
              #-  Deploying Individual Services Using Helm: product-guides/Foundational & Workload Security/26 Deploying Individual Services Using Helm.md
        # -  Recommended Service Layout: product-guides/Foundational & Workload Security/24 Recommended Service Layout.md
        # -  Intel Security Libraries Binary Installation: 
        #     - Intel Security Libraries Binary Installation: product-guides/Foundational & Workload Security/25 Intel Security Libraries Binary Installation.md
        #     -  Using NATS with Intel SecL: product-guides/Foundational & Workload Security/25.0 Using NATS with Intel SecL.md
        #     -  Installing and Configuring the Database: product-guides/Foundational & Workload Security/25.1 Installing and Configuring the Database.md
        #     -  Installing the Certificate Management Service: product-guides/Foundational & Workload Security/25.2 Installing the Certificate Management Service.md
        #     -  Installing the Authentication and Authorization Service: product-guides/Foundational & Workload Security/25.3 Installing the Authentication and Authorization Service.md
        #     -  Installing the Host Verification Service: product-guides/Foundational & Workload Security/25.4 Installing the Host Verification Service.md
        #     -  Installing the Workload Service: product-guides/Foundational & Workload Security/25.6 Installing the Workload Service.md
        #     -  Installing the Trust Agent for Linux: product-guides/Foundational & Workload Security/25.7 Installing the Trust Agent for Linux.md
        #     -  Installing the Workload Agent: product-guides/Foundational & Workload Security/25.8 Installing the Workload Agent.md
        #     -  Provisioning the Trust Agent: product-guides/Foundational & Workload Security/25.9 Provisioning the Trust Agent.md
        #     -  Installing the Intel SecL Kubernetes Extensions and Integration Hub: product-guides/Foundational & Workload Security/25.10 Installing the Intel SecL Kubernetes Extensions and Integration Hub.md
        #     -  Installing the Key Broker Service: product-guides/Foundational & Workload Security/25.11 Installing the Key Broker Service.md
        #     -  Installing the Workload Policy Manager: product-guides/Foundational & Workload Security/25.12 Installing the Workload Policy Manager.md
        # -  Intel® Security Libraries Container Deployment: product-guides/Foundational & Workload Security/30 Intel® Security Libraries Container Deployment.md
        -  Authentication: product-guides/Foundational & Workload Security/40 Authentication.md
        -  Connection Strings: product-guides/Foundational & Workload Security/50 Connection Strings.md
        -  Endorsement Certificate Pre-Registration: product-guides/Foundational & Workload Security/59 Endorsement Certificate Pre-Registration.md
        -  Platform Integrity Attestation: product-guides/Foundational & Workload Security/60 Platform Integrity Attestation.md
        -  Trusted Workload Placement: product-guides/Foundational & Workload Security/65 Trusted Workload Placement.md
        -  Workload Confidentiality: product-guides/Foundational & Workload Security/70 Workload Confidentiality.md
        # -  Trusted Virtual Kubernetes Worker Nodes: product-guides/Foundational & Workload Security/80 Trusted Virtual Kubernetes Worker Nodes.md
        -  Flavor Management: product-guides/Foundational & Workload Security/90 Flavor Management.md
        -  Scalability and Sizing: product-guides/Foundational & Workload Security/100 Scalability and Sizing.md
        -  Intel Security Libraries Configuration Settings: 
            - Changing Configuration Settings: product-guides/Foundational & Workload Security/110.0 Changing Configuration Settings.md
            - Configuration Settings (Verification Services): product-guides/Foundational & Workload Security/110.3 HVS Setup Task and Configuration Settings.md
            - Configuration Settings (Trust Agent): product-guides/Foundational & Workload Security/110.6 Trust Agent Setup Task and Configuration Settings.md
            - Configuration Settings (Integration Hub): product-guides/Foundational & Workload Security/110.9 Integration Hub Setup Task and Configuration Settings.md
            - Configuration Settings (Certificate Management Services): product-guides/Foundational & Workload Security/110.1 CMS Setup Task and Configuration Settings.md
            - Configuration Settings (Authentication and Authorization Service): product-guides/Foundational & Workload Security/110.2 AAS Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Service): product-guides/Foundational & Workload Security/110.4 WLS Setup Task and Configuration Settings.md
            - Configuration Settings (Key Broker Service): product-guides/Foundational & Workload Security/110.5 KBS Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Agent): product-guides/Foundational & Workload Security/110.7 Workload Agent Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Policy Manager): product-guides/Foundational & Workload Security/110.8 WPM Setup Task and  Configuration Settings.md
        -  Certificate and Key Management: product-guides/Foundational & Workload Security/120 Certificate and Key Management.md
        -  Upgrades: product-guides/Foundational & Workload Security/130 Upgrades.md
        -  Appendix: product-guides/Foundational & Workload Security/999 Appendix.md
      - SGX Infrastructure and Secure Key Caching:
        -  Product Guide: product-guides/SGX Infrastructure/01.md
        -  Introduction: product-guides/SGX Infrastructure/1Introduction.md
        -  SGX Attestation Infrastructure : product-guides/SGX Infrastructure/2SGX Attestation Infrastructure.md
        -  Secure Key Caching: product-guides/SGX Infrastructure/2.1Secure Key Caching.md
        -  Intel® Security Libraries Installation: product-guides/SGX Infrastructure/3Intel® Security Libraries Installation.md
        -  Authentication: product-guides/SGX Infrastructure/4Authentication.md
        -  SGX Features Provisioning: product-guides/SGX Infrastructure/5SGX Features Provisioning.md
        -  Setup Task Flows for K8s Deployments: product-guides/SGX Infrastructure/6Setup Task Flows for K8s Deployments.md
        -  Configuration Update Flows for K8s Deployments: product-guides/SGX Infrastructure/7Configuration Update Flows for K8s Deployments.md
        -  Intel Security Libraries Configuration Settings: product-guides/SGX Infrastructure/8Intel Security Libraries Configuration Settings.md
        -  Uninstallation: product-guides/SGX Infrastructure/9Uninstallation.md
        -  Binary Upgrades: product-guides/SGX Infrastructure/10Binary Upgrades.md
        -  Container Upgrades: product-guides/SGX Infrastructure/11Container Upgrades.md
        -  Appendix: product-guides/SGX Infrastructure/12Appendix.md
        -  KBS key-transfer flow validation: product-guides/SGX Infrastructure/13KBS key-transfer flow validation.md
        -  Note on Key Transfer Policy: product-guides/SGX Infrastructure/14Note on Key Transfer Policy.md
        -  Note on SKC Library Deployment: product-guides/SGX Infrastructure/15Note on SKC Library Deployment.md
  - Supplementary Guide:
      - Common Cluster Deployment:
        - Pre-requisites: supplementary-guides/Common Cluster Deployment Guide/1Pre-requisites.md
        - Deployment Architecture: supplementary-guides/Common Cluster Deployment Guide/2Deployment Architecture.md
        - Deployment Steps: supplementary-guides/Common Cluster Deployment Guide/3Deployment Steps.md
        - Workload POD Launch Validation: supplementary-guides/Common Cluster Deployment Guide/4Workload POD Launch Validation.md
        - Appendix: supplementary-guides/Common Cluster Deployment Guide/5Appendix.md
  - Release Notes:
      - Release Notes: ReleaseNotes/ReleaseNotes.md
theme:
   name: material
   font: 
     code: Fira Code
     text: Helvetica               
   palette:
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
   logo: images/isecl-logo.png
   favicon: images/isecl-logo.png
   icon:
    repo: fontawesome/brands/github
   features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.suggest
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - markdown.extensions.tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike