# Repository
repo_name: intel-secl
repo_url: https://github.com/intel-secl/intel-secl
site_name: Intel® SecL-DC
plugins:
  - search 
  - mkdocs-nav-enhancements
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`


nav: 
  - Home:
    - Intel® Security Libraries for Data Center (Intel® SecL-DC): index.md
  - Product Guide: 
      - Foundational and Workload Security:
        -  Disclaimer: Intel Disclaimer.md
        -  Introduction: product-guides/Foundational & Workload Security/02 Introduction.md
        -  Intel® Security Libraries Components: product-guides/Foundational & Workload Security/20 Intel® Security Libraries Components.md
        -  Hardware Security Technology Considerations: product-guides/Foundational & Workload Security/23 Hardware Security Technology Considerations.md
        -  Building the Intel SecL-DC Container Images: product-guides/Foundational & Workload Security/23.9 Building the Intel SecL-DC Container Images.md
        -  Deploying Intel SecL-DC Using Helm: 
              -  Deploying Intel SecL-DC Using Helm: product-guides/Foundational & Workload Security/24 Deploying Intel SecL using Helm.md
              -  Deploying Intel SecL Use Cases Using Helm: product-guides/Foundational & Workload Security/25 Deploying Intel SecL Use Cases Using Helm.md
              -  Installing the Workload Policy Manager (Workload Confidentiality Only): product-guides/Foundational & Workload Security/25.12 Installing the Workload Policy Manager.md
        -  Authentication: product-guides/Foundational & Workload Security/40 Authentication.md
        -  Connection Strings: product-guides/Foundational & Workload Security/50 Connection Strings.md
        -  Endorsement Certificate Pre-Registration: product-guides/Foundational & Workload Security/59 Endorsement Certificate Pre-Registration.md
        -  Platform Integrity Attestation: product-guides/Foundational & Workload Security/60 Platform Integrity Attestation.md
        -  Trusted Workload Placement: product-guides/Foundational & Workload Security/65 Trusted Workload Placement.md
        -  Workload Confidentiality: product-guides/Foundational & Workload Security/70 Workload Confidentiality.md
        -  Flavor Management: product-guides/Foundational & Workload Security/90 Flavor Management.md
        -  Scalability and Sizing: product-guides/Foundational & Workload Security/100 Scalability and Sizing.md
        -  Deploying Individual Services Using Helm: product-guides/Foundational & Workload Security/105 Deploying Individual Services Using Helm.md
        -  Helm charts Cleanup: product-guides/Foundational & Workload Security/106 Helm charts Cleanup.md
        -  Intel Security Libraries Configuration Settings: 
            - Changing Configuration Settings: product-guides/Foundational & Workload Security/110.0 Changing Configuration Settings.md
            - Configuration Settings (Verification Services): product-guides/Foundational & Workload Security/110.3 HVS Setup Task and Configuration Settings.md
            - Configuration Settings (Trust Agent): product-guides/Foundational & Workload Security/110.6 Trust Agent Setup Task and Configuration Settings.md
            - Configuration Settings (Integration Hub): product-guides/Foundational & Workload Security/110.9 Integration Hub Setup Task and Configuration Settings.md
            - Configuration Settings (Certificate Management Services): product-guides/Foundational & Workload Security/110.1 CMS Setup Task and Configuration Settings.md
            - Configuration Settings (Authentication and Authorization Service): product-guides/Foundational & Workload Security/110.2 AAS Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Service): product-guides/Foundational & Workload Security/110.4 WLS Setup Task and Configuration Settings.md
            - Configuration Settings (Key Broker Service): product-guides/Foundational & Workload Security/110.5 KBS Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Agent): product-guides/Foundational & Workload Security/110.7 Workload Agent Setup Task and Configuration Settings.md
            - Configuration Settings (Workload Policy Manager): product-guides/Foundational & Workload Security/110.8 WPM Setup Task and  Configuration Settings.md
        -  Certificate and Key Management: product-guides/Foundational & Workload Security/120 Certificate and Key Management.md
        -  Upgrades: product-guides/Foundational & Workload Security/130 Upgrades.md
        -  Appendix: product-guides/Foundational & Workload Security/999 Appendix.md
  - Release Notes:
      - Release Notes: ReleaseNotes/ReleaseNotes.md
theme:
   name: material
   font: 
     code: Fira Code
     text: Helvetica               
   palette:
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
   logo: images/isecl-logo.png
   favicon: images/isecl-logo.png
   icon:
    repo: fontawesome/brands/github
   features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.suggest
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - markdown.extensions.tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike